# Generated by Django 5.0.6 on 2024-07-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_address_alter_item_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='phone',
        ),
        migrations.AddField(
            model_name='item',
            name='birthday',
            field=models.CharField(default='Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='contact_no',
            field=models.TextField(default='Default Address', max_length=11),
        ),
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(default='Default Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(default='Default Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='first_name',
            field=models.CharField(default='Default Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_name',
            field=models.TextField(default='Default Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='middle_name',
            field=models.CharField(default='Default Address', max_length=100),
        ),
    ]
