# Generated by Django 5.0.6 on 2024-07-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_item_phone_item_birthday_item_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='birthday',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='contact_no',
            field=models.TextField(max_length=11),
        ),
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
    ]
