# Generated by Django 5.0.6 on 2024-07-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_item_address_alter_item_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='father_no',
            field=models.CharField(default='Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='sibling1',
            field=models.CharField(default='Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='sibling2',
            field=models.CharField(default='Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='sibling3',
            field=models.CharField(default='Default Address', max_length=100),
        ),
    ]
