# Generated by Django 5.0.6 on 2024-07-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_father_no_item_sibling1_item_sibling2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='father_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='sibling1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='sibling2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='sibling3',
            field=models.CharField(max_length=100),
        ),
    ]
